name: kit-streamlit-heroku
channels:
- conda-forge
dependencies:
- python=3.7
- conda
- pandas
- matplotlib
- numpy
- scipy
- scikit-learn
- plotly
- opencv
- scikit-image
- pip
- pip:
  - streamlit
  - collections-extended
